language: php

php:
    - 7.2
    - 7.3
    - 7.4snapshot

install:
    - travis_retry composer install --no-interaction --no-progress

script:
    - vendor/bin/tester tests -s -j 1

after_failure:
    - for i in $(find tests -name \*.expected); do echo "--- $i"; cat $i; echo; echo; done
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
    include:
        -   env: title="Lowest Dependencies"
            install:
                    - travis_retry composer update --no-interaction --no-progress --prefer-lowest --prefer-stable

        -   stage: Code Standard Checker
            php: 7.2
            install:
                - travis_retry composer create-project nette/code-checker temp/code-checker --no-interaction --no-progress
                - travis_retry composer create-project nette/coding-standard temp/coding-standard dev-master --no-interaction --no-progress

            script:
                - php temp/code-checker/src/code-checker.php --short-arrays --strict-types
                - php temp/coding-standard/ecs check src tests --config temp/coding-standard/coding-standard-php71.neon

        -   stage: Code Coverage
            script:
                - vendor/bin/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src

            after_script:
                - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
                - php coveralls.phar --verbose --config tests/.coveralls.yml

    allow_failures:
        - stage: Code Standard Checker
        - stage: Code Coverage

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
